### PR TITLE
add node-pre-gyp support

### PR DESCRIPTION
**Pull request by b-ono**
This PR modifies electron-rebuild to use node-pre-gyp if the binary section is present. It uses the --fallback-to-build option to build the dependency if no prebuild binary is available.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Can you explain exactly what this achieves, as far as I am aware `node-pre-gyp` is 100% incompatible with Electron binaries and this `fallback-to-build` is semantically equivalent to our existing `node-gyp` logic?

**Comment by b-ono** [comment]
node-pre-gyp can build the packages for electronif the runtime and disturl and so on is specified correctly. It can also download the prebuild packages from the specified host. 

`fallback-to-build` should be equivalent to the existing `node-gyp` logic.

**Comment by MarshallOfSound** [comment]
As far as I am aware `node-pre-gyp --fallback-to-build` is just a complicated wrapper around `node-gyp` and this module actually exists to fix numerous issues with using `node-pre-gyp` so I'd like to avoid using it.

If this PR actually fixes a bug please raise that as an issue and we can look at solving it without bring in the `pre-gyp` dependency

**Comment by roytan883** [comment]
@MarshallOfSound `node-pre-gyp` is very useful when the module already has binary pre-build. for example, use electron with `realm-js` which has:
```
  "binary": {
    "module_name": "realm",
    "module_path": "./compiled/{node_abi}_{platform}_{arch}/",
    "host": "https://static.realm.io",
    "remote_path": "/node-pre-gyp/{version}/"
  }
```
so `node-pre-gyp` will download it from 
`https://static.realm.io/node-pre-gyp/2.29.2/realm-v2.29.2-electron-v4.2-win32-x64.tar.gz`.
This `tar.gz` only include a  single file `realm.node` already pre-build.

please consider add `node-pre-gyp` support. Because `electron-forge` depend on `electron-rebuild` but `electron-rebuild` not support `node-pre-gyp`.

**Pull request closed without merging**
