### PR TITLE
chore: use @napi-rs/lzma to replace lzma-native

### PR DESCRIPTION
**Pull request by Brooooooklyn**
See https://github.com/Brooooooklyn/lzma

`@napi-rs/lzma` support more platform and easier to install (without node-gyp/node-pre-gyp).

### CODE REVIEW

**Comment by malept** [comment]
What platforms are you looking to support that lzma-native doesn't already support with a prebuilt module?

As much as I like Rust, I'm hesitant to add a dependency on a module that could possibly add a dependency on Rust itself.

Also FWIW the readme for `lzma-native` is a little out of date, it currently uses `prebuildify` / `node-gyp-build` to handle the native module building/bundling.

**Comment by Brooooooklyn** [comment]
> What platforms are you looking to support that lzma-native doesn't already support with a prebuilt module?

Like `linux-x64-musl/linux-aarch64-musl`, `windows-aarch64` and FreeBSD.

> As much as I like Rust, I'm hesitant to add a dependency on a module that could possibly add a dependency on Rust itself.

Don't worry about it, you can even use this package in scratch Docker image like `node:lts-alpine`. It's been fully prebuilt.

**Comment by malept** [comment]
> Like `linux-x64-musl/linux-aarch64-musl`, `windows-aarch64` and FreeBSD.

As far as I can tell, `lzma-native` supports `linux-arm64` and `windows-arm64`. I'm not particularly concerned about FreeBSD since Electron doesn't officially support it.

**Comment by Brooooooklyn** [comment]
lzma-native support `linux-x64-gnu/linux-aarch64-gnu` but not support `linux-x64-musl/linux-aarch64-musl`.

But I'm not sure if there were developers use electron on `musl` linux platform.

**Comment by malept** [comment]
> lzma-native support `linux-x64-gnu/linux-aarch64-gnu` but not support `linux-x64-musl/linux-aarch64-musl`.
> 
> But I'm not sure if there were developers use electron on `musl` linux platform.

Electron itself requires glibc, so I doubt it.

**Comment by Brooooooklyn** [comment]
And this pull request will absolutely resolve issues like this: https://github.com/addaleax/lzma-native/issues/102

**Comment by pbrit** [comment]
> > Like `linux-x64-musl/linux-aarch64-musl`, `windows-aarch64` and FreeBSD.
> 
> As far as I can tell, `lzma-native` supports `linux-arm64` and `windows-arm64`. I'm not particularly concerned about FreeBSD since Electron doesn't officially support it.

I believe the above is correct, however, it doesn't support `darwin-arm64` which is getting more abundant with advent of Apple's `M1 CPU`. 

This PR did fix my troubles with `lzma-native` (_I'm proud Apple M1 user_), and  `@napi-rs/lzma` seems to be a quite neat approach.

@Brooooooklyn @malept Is there anything I can do to get it merged? 

Merci @Brooooooklyn !

**Comment by malept** [comment]
> > > Like `linux-x64-musl/linux-aarch64-musl`, `windows-aarch64` and FreeBSD.
> > 
> > 
> > As far as I can tell, `lzma-native` supports `linux-arm64` and `windows-arm64`. I'm not particularly concerned about FreeBSD since Electron doesn't officially support it.
> 
> I believe the above is correct, however, it doesn't support `darwin-arm64` which is getting more abundant with advent of Apple's `M1 CPU`.
> 
> This PR did fix my troubles with `lzma-native` (_I'm proud Apple M1 user_), and `@napi-rs/lzma` seems to be a quite neat approach.
> 
> @Brooooooklyn @malept Is there anything I can do to get it merged?
> 
> Merci @Brooooooklyn !

I asked about darwin-arm64 support in https://github.com/addaleax/lzma-native/issues/118. This PR is on hold until then.

**Comment by Brooooooklyn** [comment]
Any progress?

**Comment by Brooooooklyn** [comment]
@malept ready to merge again

**Comment by beorn** [comment]
This does solve a problem: Currently there doesn't seem to be any way to run electron-forge properly on M1 Macs:

 - lzma-native is broken for M1 macs https://github.com/addaleax/lzma-native/pull/123
 - arch=x86 is broken on M1 macs https://github.com/electron/electron/pull/32266

So there are no workarounds.

Looking a bit at xc/libzma it does seem fickle and old vs @napi-rs/lzma - so maybe worth switching?

**Pull request closed without merging**
