### PR TITLE
Update the README with fixed examples, async/await, mention Node

### PR DESCRIPTION
**Pull request by ide**
- Fixes the examples so that the version numbers are no longer prefixed with `v`, which no longer works with Electron 1.3.1 on macOS at least. With `v` you get an error about common.gypi missing.
- Update one of the examples to use async/await and have fewer hardcoded values
- Change io.js references to Node.js

### CODE REVIEW

**Comment by zeke** [comment]
I haven't tested that code but the doc changes look good to me.

**Comment by ide** [comment]
I run almost the same code in my build script and it's working for what that's worth.

**Comment by MarshallOfSound** [comment]
Node doesn't have native support for `async` and `await` yet does it?

Should we really be giving example syntax that won't work without boilerplating with a transpiler like babel?

**Comment by paulcbetts** [comment]
I intentionally didn't use async/await so that people wouldn't think it was required

**Comment by ide** [comment]
I think it depends on whether the intent is to provide copy-pasteable code or to communicate the usage clearly. @paulcbetts want me to change it back if you think it's going to cause issues?

**Comment by zeke** [comment]
@ide are you okay with scrapping the refactored code from this PR and just leaving the readme fixes?

**Comment by ide** [comment]
@zeke I reverted to the original code and added in the snippet to programmatically get the Electron version, if you think that nets out being helpful.

**Comment by zeke** [comment]
Definitely helpful, if even just for this:

> With `v` you get an error about common.gypi missing.

**Pull request merged**
