### PR TITLE
fix: Update to node-gyp 7

### PR DESCRIPTION
**Pull request by adamretter**
node-gyp 7 has some improvements for building on Catalina and building with Python3 etc.

### CODE REVIEW

**Comment by malept** [comment]
This will trigger a semver-major release of electron-rebuild, as node-gyp requires a recent version of Node 10. Please hold off on approving this.

**Comment by adamretter** [comment]
@malept Isn't a recent version of Node 10 a good idea? Node10 is already no longer actively developed and will soon be EOL - https://nodejs.org/en/about/releases/

**Comment by malept** [comment]
Yes, however:

1. This needs to be explicit. If this PR was merged as-is, it would be released as a patch, not a major version bump.
2. I have an in-progress branch to update all of the other dependencies that now require Node 10 and I would personally prefer to do all of that together, to avoid multiple version bumps in succession.

**Comment by malept** [comment]
A workaround for now would be to use yarn resolutions in your projects to resolve any node-gyp dependencies to whatever version you need.

**Comment by malept** [comment]
I've upgraded node-gyp to version 7 in the version 2 branch, thanks for letting me know about the version bump.

**Comment by adamretter** [comment]
@malept Is there any sort of timeframe for a version 2 release of electron-rebuild?

**Comment by malept** [comment]
Roadmap: https://github.com/electron/electron-rebuild/issues/356

**Pull request closed without merging**
